import AppContainer from "@/components/AppContainer";
import { Provider } from "jotai";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <NextIntlClientProvider>
          <Provider>
            <AppContainer>
              {children}
            </AppContainer>
          </Provider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
