import AppContainer from "@/components/AppContainer";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <html>
      <body>
        <NextIntlClientProvider>
          <AppContainer>
            {children}
          </AppContainer>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
