// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "home": {
    "title": "CivicSphere",
    "description": "A platform for civic engagement and community collaboration.",
    "getStarted": "Get Started",
    "signIn": "Sign In",
    "features": {
      "communityDiscussions": {
        "title": "Community Discussions",
        "description": "Join local conversations about issues that matter to your neighborhood with verified content."
      },
      "clearDoubts": {
        "title": "Clear all your doubts",
        "description": "Ultimate AI Chatbot which is updated and trained to answer all your queries related to civic issues and services."
      },
      "accessible": {
        "title": "Accessible and Inclusive",
        "description": "Discover local resources and civic opportunities curated for your area in an accessible and inclusive manner."
      }
    }
  },
  "auth": {
    "heroTitle": "Welcome to CivicSphere",
    "heroSubtitle": "Join your community — discover, discuss and act.",
    "onboardTitle": "Complete Your Onboarding",
    "signupTitle": "Create Your Account",
    "signinTitle": "Welcome Back",
    "tabSignup": "Sign Up",
    "tabSignin": "Sign In",
    "loading": "Loading..."
  },
  "chat": {
    "suggestions": {
      "housing": "What's the current situation with housing prices and trends in New York City neighborhoods (e.g., Manhattan) and nearby suburbs?",
      "elections": "When are my local elections, how do I cast a ballot, and who is contesting in my area?",
      "judicial": "What is the role of a federal judge and how does it differ from other political or judicial positions?"
    },
    "labels": {
      "you": "You",
      "assistant": "Assistant",
      "typing": "Typing..."
    },
    "inputPlaceholder": "Enter text to chat with AI",
    "tooltip": {
      "clearHistory": "Clear chat history"
    },
    "mic": {
      "captured": "This is a simulated voice message transcribed."
    },
    "errors": {
      "generic": "Sorry, there was an error processing your request. Please try again."
    }
  },
  "tags": {
    "affordable-housing": "Affordable Housing {name}",
    "artificial-intelligence": "Artificial Intelligence",
    "arts-and-culture": "Arts And Culture",
    "asian-voices": "Asian Voices",
    "atheist-voices": "Atheist Voices",
    "ballot-questions": "Ballot Questions",
    "baptist-voices": "Baptist Voices",
    "bipoc-voices": "Bipoc Voices",
    "black-voices": "Black Voices",
    "buddhist-voices": "Buddhist Voices",
    "catholic-voices": "Catholic Voices",
    "civic-education": "Civic Education",
    "civic-participation": "Civic Participation",
    "civil-rights": "Civil Rights",
    "climate-action": "Climate Action",
    "clothing-and-fashion": "Clothing And Fashion",
    "colored-voices": "Colored Voices",
    "community-development": "Community Development",
    "community-initiatives": "Community Initiatives",
    "cultural-diversity": "Cultural Diversity",
    "cultural-representation": "Cultural Representation",
    "digital-access": "Digital Access",
    "disability-rights": "Disability Rights",
    "disease-prevention": "Disease Prevention",
    "economic-justice": "Economic Justice",
    "economics": "Economics",
    "education": "Education",
    "education-access": "Education Access",
    "education-for-all": "Education For All",
    "elections-and-voting": "Elections And Voting",
    "emergency-preparedness": "Emergency Preparedness",
    "environmental-rights": "Environmental Rights",
    "financial-literacy": "Financial Literacy",
    "food-security": "Food Security",
    "future-of-work": "Future Of Work",
    "gender-equality": "Gender Equality",
    "gender-justice": "Gender Justice",
    "government-policy": "Government Policy",
    "health-equity": "Health Equity",
    "healthcare-access": "Healthcare Access",
    "housing-rights": "Housing Rights",
    "human-rights": "Human Rights",
    "indigenous-voices": "Indigenous Voices",
    "immigrant-voices": "Immigrant Voices",
    "income-inequality": "Income Inequality",
    "interfaith-dialogue": "Interfaith Dialogue",
    "infrastructure": "Infrastructure",
    "interracial-relationships": "Interracial Relationships",
    "lgbtq-voices": "Lgbtq Voices",
    "local-economies": "Local Economies",
    "media-literacy": "Media Literacy",
    "mental-health": "Mental Health",
    "migrant-rights": "Migrant Rights",
    "mothers-rights": "Mothers Rights",
    "native-american-voices": "Native American Voices",
    "national-security": "National Security",
    "natural-disasters": "Natural Disasters",
    "neighborhoods": "Neighborhoods",
    "nuclear-disarmament": "Nuclear Disarmament",
    "pagan-voices": "Pagan Voices",
    "pandemic-response": "Pandemic Response",
    "parenting-rights": "Parenting Rights",
    "personal-finance": "Personal Finance",
    "philanthropy": "Philanthropy",
    "prison-reform": "Prison Reform",
    "progressive-values": "Progressive Values",
    "public-health": "Public Health",
    "racial-justice": "Racial Justice",
    "refugee-rights": "Refugee Rights",
    "religious-freedom": "Religious Freedom",
    "reproductive-rights": "Reproductive Rights",
    "school-safety": "School Safety",
    "social-justice": "Social Justice",
    "sports-and-recreation": "Sports And Recreation",
    "sustainability": "Sustainability",
    "technology-access": "Technology Access",
    "veteran-rights": "Veteran Rights",
    "violence-prevention": "Violence Prevention",
    "voter-rights": "Voter Rights",
    "water-rights": "Water Rights",
    "women-empowerment": "Women Empowerment"
  }
};
export default messages;