import { Language } from "./types";

export const BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL;

export const LANGS: Language[] = [
  { code: "de", name: "Deutsch" },
  { code: "el", name: "Ελληνικά" },
  { code: "en", name: "English" },
  { code: "es", name: "Español" },
  { code: "fr", name: "Français" },
  { code: "hi", name: "हिन्दी" },
  { code: "it", name: "Italiano" },
  { code: "ja", name: "日本語" },
  { code: "ko", name: "한국어" },
  { code: "pl", name: "Polski" },
  { code: "pt", name: "Português" },
  { code: "ru", name: "Русский" },
  { code: "zh", name: "中文" }
]

export const LOCALES = LANGS.map(lang => lang.code);

export const TAGS = [
  'affordable-housing',
  'artificial-intelligence',
  'arts-and-culture',
  'asian-voices',
  'atheist-voices',
  'ballot-questions',
  'baptist-voices',
  'bipoc-voices',
  'black-voices',
  'buddhist-voices',
  'catholic-voices',
  'civic-education',
  'civic-participation',
  'civil-rights',
  'climate-action',
  'clothing-and-fashion',
  'colored-voices',
  'community-development',
  'community-initiatives',
  'cultural-diversity',
  'cultural-representation',
  'digital-access',
  'disability-rights',
  'disease-prevention',
  'economic-justice',
  'economics',
  'education',
  'education-access',
  'education-for-all',
  'elections-and-voting',
  'emergency-preparedness',
  'environmental-rights',
  'financial-literacy',
  'food-security',
  'future-of-work',
  'gender-equality',
  'gender-justice',
  'government-policy',
  'health-equity',
  'healthcare-access',
  'housing-rights',
  'human-rights',
  'immigrant-voices',
  'income-inequality',
  'indigenous-voices',
  'infrastructure',
  'interfaith-dialogue',
  'interracial-relationships',
  'lgbtq-voices',
  'local-economies',
  'media-literacy',
  'mental-health',
  'migrant-rights',
  'mothers-rights',
  'national-security',
  'native-american-voices',
  'natural-disasters',
  'neighborhoods',
  'nuclear-disarmament',
  'pagan-voices',
  'pandemic-response',
  'parenting-rights',
  'personal-finance',
  'philanthropy',
  'prison-reform',
  'progressive-values',
  'public-health',
  'racial-justice',
  'refugee-rights',
  'religious-freedom',
  'reproductive-rights',
  'school-safety',
  'social-justice',
  'sports-and-recreation',
  'sustainability',
  'technology-access',
  'veteran-rights',
  'violence-prevention',
  'voter-rights',
  'water-rights',
  'women-empowerment'
]
