name: Build the frontend

on:
  push:
    branches:
      - main
    paths:
      - "frontend/src/**"

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image for Frontend
      run: |
        docker build -f ./frontend/Dockerfile --build-arg NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }} -t ${{ secrets.PROJECT_NAME }}-frontend:latest ./frontend
